### ISSUE TITLE
reddit comments not displayed

### ISSUE THREAD

**Issue by SriRamanujam** [SriRamanujam/bot-modules#32]
Issue reported by tripgod (tripgod!~slipgod@ip68-8-2-107.sd.sd.cox.net) in channel #casualteam:

when a link to a comment on reddit is posted, LazyBot_v3 no longer says what the comment says

**Comment by brinskoj** [comment]
Example of comment where this is true
https://www.reddit.com/r/pokemongo/comments/4s594s/riding_shotgun_has_a_new_set_of_responsibilities/d56u4bg
