### ISSUE TITLE
Relay a message when user becomes active again

### ISSUE THREAD

**Issue by brinskoj** [SriRamanujam/bot-modules#5]
It would be super handy if the bot relays a message to somebody when that person first speaks.

example:
<mlue>.tell phil hey I forgot to tell you that I got a new phone.
....... some time later .....
<phil> what up guys, I'm back
<LazyBot_v3> phil, mlue said 9h 3m ago: "hey I forgot to tell you that I got a new phone."

**Comment by SriRamanujam** [comment]
Finally got around to this. Test it out, let me know how it goes.

**Comment by brinskoj** [comment]
Any plan for having the bot respond when the user speaks instead of just joining channel? 

Here is how I imagine the execution:
15-17:10 +    the8chman : .tell Lightning a hoe is a hoe
15-17:10 @ DeepThroat : The operation succeeded.
15-17:11 +    the8chman : .tell Galactica hoe dat sheeit
15-17:11 @ DeepThroat : The operation succeeded.
15-17:11 @  Galactica : um
15-17:11 @ DeepThroat : Galactica: Sent just now: <the8chman> hoe dat sheeit
